#!/bin/bash

# if less than two arguments supplied, display usage 
if [  $# -lt 1 ] 
then 
	echo "Usage: ./program <hexfile>"
	exit 1
fi 

espeak "Programming"
make fuse
make firmware HEX=$1

if [ $? -eq 0 ]
then espeak "Complete"
else espeak "Failed"
fi
