#!/bin/bash

while [ true ]
do
	make read > /dev/null 2> /dev/null

	while [ $? -ne 0 ]
	do
		echo -n .
		make read > /dev/null 2> /dev/null
	done

	espeak "Programming"

	echo -e "\n\033[1;33mFusing...\033[0m\n"
	make fuse

	echo -e "\n\033[1;33mProgramming...\033[0m\n"
	make firmware HEX=hex/cicada.hex
	
	echo -e "\n\033[1;33mGenerating EEPROM...\033[0m\n"
	python3 generateEE.py

	head -n1 cicada.eep

	make eeprom

	if [ $? -eq 0 ]
	then 
		echo -e "\033[0;32mComplete\033[0m\n"
		espeak "Complete"
	else 
		echo -e "\033[0;31mFailed\033[0m\n"
		espeak "Failed"
	fi

done
