#!/bin/bash

f=${1%.*}
fname=$(basename $f)
echo $fname

xxd -i -s +44 $1 > $fname.h
sed -i '1s/^/#include <avr\/pgmspace.h>\n\n/' $fname.h
sed -i "s/.*_wav\[\]/const uint8_t wav[]/" $fname.h
sed -i "s/.*_wav_len/const uint16_t wav_len/" $fname.h
sed -i "s/wav\[\]/wav[] PROGMEM/" $fname.h
